// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOczkwsZxC7g1m9m2yzqBCrF87D_-k-nA',
    appId: '1:261806783247:android:a87b3555a2d6604f1d1c7a',
    messagingSenderId: '261806783247',
    projectId: 'myfitnesspalproject-cebea',
    storageBucket: 'myfitnesspalproject-cebea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM4K_75kQ-Ks-Tr2Xd2lIRGX5kQwLd-Y8',
    appId: '1:261806783247:ios:9ea1183e9a4a944c1d1c7a',
    messagingSenderId: '261806783247',
    projectId: 'myfitnesspalproject-cebea',
    storageBucket: 'myfitnesspalproject-cebea.appspot.com',
    iosClientId: '261806783247-7povjsomlqeqf93d5kjnvq2cdfh9vn1p.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessApplicationProject',
  );
}
